### ISSUE TITLE
input string out of range

### ISSUE THREAD

**Issue by tjt263** [delihiros/pseudogen#1]
<pre><code># user@droid:/git/pseudogen$ ./run-pseudogen.sh
# def f(x):
#    if x == 0:
#        return 1
#    a = f(x-1)
#    b = f(x-2)
#    return a + b
'''
Traceback (most recent call last):
  File "/git/pseudogen/scripts/head-insertion.py", line 30, in <module>
    main()
  File "/git/pseudogen/scripts/head-insertion.py", line 24, in main
    insert_head(t)
  File "/git/pseudogen/scripts/head-insertion.py", line 8, in insert_head
    if t.label()[0].isupper() and not isinstance(t[0], str):
IndexError: string index out of range
'''
#############################################################################
# user@droid:/git/pseudogen$ cat scripts/head-insertion.py
from nltk.tree import Tree
import sys

def insert_head(t):
    if isinstance(t, Tree):
        for ch in t:
            insert_head(ch)
        if t.label()[0].isupper() and not isinstance(t[0], str):
            t.insert(0, Tree('HEAD', [t.label()]))

def encode(t):
    if isinstance(t, Tree):
        ret = '(' + t.label()
        for ch in t:
            ret += ' ' + encode(ch)
        return ret + ')'
    else:
        return str(t)

def main():
    for l in sys.stdin:
        t = Tree.fromstring(l)
        insert_head(t)
        print(encode(t))
        sys.stdout.flush()

if __name__ == '__main__':
    main()
#############################################################################
# https://github.com/delihiros/pseudogen/
# http://ahclab.naist.jp/pseudogen/
</code></pre>

**Comment by delihiros** [comment]
could not produce with Ubuntu 16.04 with Python 3.5-dev.
would you give me some info about what  OS and Python version you are using?
apart from that you need to specify a travatar configuration file with -f option in order to run run-pseudogen scripts.

**Comment by delihiros** [comment]
this bug is fixed in a263c0d.
closing.
