### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by tjt263** [delihiros/pseudogen#2]
<pre><code># user@droid:/git/pseudogen$ ./run-pseudogen.sh -f ./data/tune/travatar.ini
# def f(x):
#    if x == 0:
#        return 1
#    a = f(x-1)
#    b = f(x-2)
#    return a + b
'''
Traceback (most recent call last):
  File "/git/pseudogen/scripts/head-insertion.py", line 30, in <module>
    main()
  File "/git/pseudogen/scripts/head-insertion.py", line 24, in main
    insert_head(t)
  File "/git/pseudogen/scripts/head-insertion.py", line 8, in insert_head
    if t.label()[0].isupper() and not isinstance(t[0], str):
IndexError: string index out of range
Traceback (most recent call last):
  File "/git/pseudogen/scripts/simplify.py", line 94, in <module>
    main()
  File "/git/pseudogen/scripts/simplify.py", line 91, in main
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
'''
</code></pre>

**Comment by amirmohammadkz** [comment]
I have this problem too.

**Comment by delihiros** [comment]
hmm looking

**Comment by delihiros** [comment]
couldn't reproduce. need further investigation to solve the problem.
would you give me some info about your environment? (OS version, python version, etc)

```
$ ../run-pseudogen.sh -f tune/travatar.ini
def f(x): [Enter]
define the method f with an argument x .

$ cat sample.py
def f(x):
   if x == 0:
       return 1
   a = f(x-1)
   b = f(x-2)
   return a + b

$ ../run-pseudogen.sh -f tune/travatar.ini < sample.py
define the method f with an argument x .
if x equals to integer 0 ,
...
```

**Comment by tjt263** [comment]
Various Unix derivitives:
Linux (Debian, Ubuntu, Android),
macOS, etc.

Python versions:
Both (2.7 & 3.6).

**Comment by tjt263** [comment]
The file `pseudogen/data/tune/travatar.ini` doesn't seem to exist.

Also, `find / -type f -name travatar.ini 2>/dev/null` returns no results.

**Comment by delihiros** [comment]
okay in that case I suppose that you did not succeed on training process.
first of all, would you check if you succeeded on installing tools, like travatar?
to do that, you might want to run the script `tool_setup.sh` line by line.

**Comment by tjt263** [comment]
I'll try that. Which version of `python` is `pseudogen` dependent on?

**Comment by delihiros** [comment]
I've tested pseudogen with 3.5-dev.

**Comment by tjt263** [comment]
Okay, so not <3.0 in other words.
I'm writing a little setup script for it, and I noticed your instructions include:
`pip install nltk` (i.e. `pip` as opposed to `pip3`).
Is that intentional?

**Comment by delihiros** [comment]
just because I usually use pyenv I wrote it that way.
havent tested with 2.7 but it might work.
and according to the error the problem is different from those version problem.

**Comment by tjt263** [comment]
`tool_setup.sh` completes successfully, but still no `pseudogen/data/tune/travatar.ini`.

**Comment by tjt263** [comment]
### Currently:
**in:**
<pre><code><b>user@host:/git/pseudogen/data$</b> ../train-pseudogen.sh -p all.code -e all.anno</code></pre>
**out:**
```
...

SUCCESS
training travatar ... 

Working directory travatar-model already exists or could not be created at /git/pseudogen/tools/travatar/script/train/train-travatar.pl line 135.
../train-pseudogen.sh: 62: ../train-pseudogen.sh: cho: not found
Executing: mkdir tune
Executing: /git/pseudogen/tools/travatar/script/train/filter-model.pl travatar-model/model/travatar.ini tune/run1.ini tune/filtered "/git/pseudogen/tools/travatar/script/train/filter-rule-table.py dev.reducedtree"
Couldn't open travatar-model/model/travatar.ini
Exit code: 2
Couldn't filter at /git/pseudogen/tools/travatar/script/mert/mert-travatar.pl line 90.
```
- - -
### Fresh Install:
**in:**
<pre><code><b>user@host:/git/pseudogen/data$</b> ../train-pseudogen.sh -p all.code -e all.anno</code></pre>
**out:**
```
...

==========================================================
Executing: /git/pseudogen/tools/travatar/script/train/symmetrize.pl travatar-model/align/src-trg.giza.A3.final travatar-model/align/trg-src.giza.A3.final > travatar-model/align/align.txt
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\({ <-- HERE  ([0-9 ]*)}\)/ at /git/pseudogen/tools/travatar/script/train/symmetrize.pl line 159.
Exit code: 2
Died at /git/pseudogen/tools/travatar/script/train/train-travatar.pl line 236.
../train-pseudogen.sh: 62: ../train-pseudogen.sh: cho: not found
Executing: mkdir tune
Executing: /git/pseudogen/tools/travatar/script/train/filter-model.pl travatar-model/model/travatar.ini tune/run1.ini tune/filtered "/git/pseudogen/tools/travatar/script/train/filter-rule-table.py dev.reducedtree"
Couldn't open travatar-model/model/travatar.ini
Exit code: 2
Couldn't filter at /git/pseudogen/tools/travatar/script/mert/mert-travatar.pl line 90.
```

**Comment by delihiros** [comment]
hmm would you send me all the logs of line by line installation as a gist or something?

**Comment by tjt263** [comment]
https://gist.github.com/tjt263/bc9d86e37ca194883c5aa126c62f9348

**Comment by delihiros** [comment]
thanks for the log.
will see if i can figure out

**Comment by tjt263** [comment]
### Update:

```
SUCCESS
training travatar ... 

Executing: mkdir travatar-model
(1) Preparing data @ Fri  8 Jun 19:48:40 AWST 2018
Executing: mkdir -p travatar-model/data
Executing: /git/pseudogen/tools/travatar/src/bin/tree-converter -input_format penn -output_format word < train.reducedtree > travatar-model/data/src.word
Main arguments:
Optional arguments:
 -input_format 	penn
 -output_format 	word
 -split 	
 -compoundsplit 	
 -compoundsplit_filler 	
 -compoundsplit_threshold 	0.01
 -compoundsplit_minchar 	3
 -binarize 	none
 -case 	none
 -flatten 	false
 -debug 	0
Transforming trees (.=10,000, !=100,000 sentences)
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: Error reading tree on line 1

ERROR: Expecting parenthesis but got '(105)i'
Aborted
Exit code: 134
Died at /git/pseudogen/tools/travatar/script/train/train-travatar.pl line 182.
tuning travatar ... 
Executing: mkdir tune
Executing: /git/pseudogen/tools/travatar/script/train/filter-model.pl travatar-model/model/travatar.ini tune/run1.ini tune/filtered "/git/pseudogen/tools/travatar/script/train/filter-rule-table.py dev.reducedtree"
Couldn't open travatar-model/model/travatar.ini
Exit code: 2
Couldn't filter at /git/pseudogen/tools/travatar/script/mert/mert-travatar.pl line 90.

```
`pseudogen/data/tune/travatar.ini` still appears to be missing.

**Comment by delihiros** [comment]
I have fixed that problem with a263c0d.
please update thanks

**Comment by delihiros** [comment]
and I am making a docker image so if you can wait I can share that

**Comment by delihiros** [comment]
fixed all the bugs.
please update to the latest or use docker image as described in README to check.
