### ISSUE TITLE
A question about the training files

### ISSUE THREAD

**Issue by Abdulaziz-Alhefdhi** [delihiros/pseudogen#4]
Dear Delihiros,
Thanks for sharing this wonderful tool.
Pseudogen generates multiple files for training. Two of them are 'train.reducedtree' and 'train.reducedsurf'. Is 'reducedtree' the tree after pruning and 'reducedsurf' the tree after pruning & simplifying? Is 'reducedsurf' the one that is labeled in your paper as Reduced-T2SMT?
Sample from 'train.reducedtree':
`(Expr (HEAD Expr) (value (Call (HEAD Call) (func (Attribute (HEAD Attribute) (value (Name os)) (attr (str remove)))) (args (list (Name fname))))))`
Sample from 'train.reducedsurf':
`Expr Call Attribute os remove fname`

**Comment by delihiros** [comment]
hi I'll take a look today

**Comment by delihiros** [comment]
hi Abdulaziz,

Sorry for late reply.

yes $PYTHON_FILE.headtree is the file that processed head insertion.
this is done by head-insertion.py.
simplify.py will do pruning and simplify and generates a $PYTHON_FILE.reducedtree.

> We developed 20 hand-written rules to
> prune and simplify the head-inserted tree by removing nodes
> that don’t seem related to the surface form of the language.

(simplify.py)
RULES = [
    (
        lambda t: t.label() == 'body' and t[0].label() == 'list' and t[0][0].label() == 'Pass'
        ,
        lambda t: None
    ),

reducedsurf file is only used for alignment by pialign but as far as I remember the current implementation of pseudogen do not use this alignment (we use giza++ instead).


you can see how the training data is created in train-pseudogen.sh.

(train-pseudogen.sh)
echo "head insertion ... " 1>&2
python3 $BASE_DIR/scripts/head-insertion.py < $PYTHON_FILE.rawtree > $PYTHON_FILE.headtree
echo "simplifying ... " 1>&2
python3 $BASE_DIR/scripts/simplify.py < $PYTHON_FILE.headtree > $PYTHON_FILE.reducedtree
python3 $BASE_DIR/scripts/filter-data.py $PYTHON_FILE.pytok $ENG_FILE.entok $PYTHON_FILE.reducedtree > all.combined


good luck for your work!
