### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KiarashS** [delihiros/pseudogen#8]
Dear,

Thanks for your great work.
How can we download the dataset?

Thanks in advance

**Comment by postatum** [comment]
I may be wrong, but I think it's described [here](https://github.com/delihiros/pseudogen#usage). The `wget`ing code piece.

**Comment by CyraxSector** [comment]
Here we go http://ahclab.naist.jp/pseudogen/en-django.tar.gz

**Comment by romiras** [comment]
This issue can be closed as resolved
